
def iniciar(): print("Registro de Pacientes no Hospital \n")
nome=input("Digite o nome: ")
idade=int(input("Digita a Idade do Paciente: "))
sexo=input("Digite o sexo do Paciente: (M/F) ")
if idade>=55:
    print ("O Paciente " +  nome + " possui atendimento prioritário! \n")
else: print ("Paciente registrado!\n")

print("Vamos registrar o serviço para a paciente")
descricao_servico=input("Descreva o atendimento requisitado para o paciente \n")

print("\n")
print("Registrado! \n")
print("\n")
print("\n")
print("Selecione uma categoria para o atendimento requisitado, por favor!\n")
print("1- Triagem\n")
print("2- Medicamento\n")
print("3- Enfermagem\n")
print("4- Urgência (sinalizar na descrição) \n")
print("5- Cancelar\n") 
print("\n")
nome_servico=input("Digite a categoria do serviço: \n")
if nome_servico=="1":print("Registrado!\n")
elif nome_servico=="2":print("Registrado!\n")
elif nome_servico=="3":print("Registrado!\n")
elif nome_servico=="4":print("Registrado!\n")
elif nome_servico=="5":print("Deseja descrever o serviço novamente ou apenas prosseguir?\n")
else: print("Categoria inválida!\n")
if nome_servico=="5":decisao_descricao=input("? (S/N) \n")
print("\n")

print("\n")
print("Obrigado por usar nosso sistema! \n")
decisao_paciente=input("Deseja cadastrar outro paciente?! (S/N)\n")
print("\n")
if decisao_paciente=="S": iniciar()
else: print("Obrigado! :)") 